server:
  port: 8805
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerCRUD
    username: root
    password:

  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 51200KB
      max-request-size: 51200KB

#  security:
#    user:
#      name: shrijana
#      password: shrijana
